// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEPgpgSf2PgB5EeYrjlhNMLev2LgAaAGA',
    appId: '1:181801802533:android:01d1de7d98915410a718cc',
    messagingSenderId: '181801802533',
    projectId: 'musang-syncronizehub-ody-3091b',
    storageBucket: 'musang-syncronizehub-ody-3091b.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBO8OdeiQhqLzTV8MEHJBm9vI_34grTL0w',
      appId: '1:181801802533:web:af11db5ed29407cca718cc',
      messagingSenderId: '181801802533',
      projectId: 'musang-syncronizehub-ody-3091b'
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAKgPz-GxZId3jT-shX1NoENEE3N2SefGA',
  //   appId: '1:304325698899:ios:1cd038169229c9df64eda6',
  //   messagingSenderId: '304325698899',
  //   projectId: 'flutter-login-app-f6e5f',
  //   storageBucket: 'flutter-login-app-f6e5f.appspot.com',
  //   iosBundleId: 'com.example.login',
  // );
}
